version: '1.0.{build}'

skip_branch_with_pr: true

max_jobs: 1

environment:
  ASPNETCORE_ENVIRONMENT: PRODUCTION

image: Visual Studio 2017

matrix:
  fast_finish: true

platform: Any CPU

configuration: Release

before_build:
  - nuget restore
  
build:
  project: AppVeyorTest.sln